name: eslint
on: [pull_request]
jobs:
  eslint:
    name: eslint with reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter.
          eslint_flags: "src/**/*.{ts,tsx}"
